### ISSUE TITLE
Not able to upload multiple certificates in quickblox dashboard

### ISSUE THREAD

**Issue by subhangiP** [QuickBlox/quickblox-flutter-samples#10]
- Uploaded voip certificate and uploaded in quickblox admin panel.
- I have created Apple Push Notification service SSL (Sandbox & Production) certificate and created .p12 file.

When i try to upload 2nd certificate getting **Error
Certificate with bundle identifier "bundleId" already uploaded. Please consider to remove current certificate if you need to upload the new one. You can use only one universal or sandbox certificate simultaneously. We recommend use single universal certificate to cover all the cases.**

PFA Screenshot 
<img width="1128" alt="Screenshot 2022-01-30 at 3 59 56 PM" src="https://user-images.githubusercontent.com/40853201/151696118-1dd89289-0aa4-4b22-ba0a-0f92d1e6f47b.png">

**Comment by ghost** [comment]
@subhangiP Hello,

This is Nikolay from QuickBlox support.

Please try using one APNS universal certificate for all types of notifications and let me know if there are any issues.

Feel free to use these guides:
https://help.quickblox.com/article/357-how-do-i-configure-chat-and-video-calling-push-notifications-and-offline-messaging
https://help.quickblox.com/article/359-does-quickblox-support-voip-notifications-for-ios

**Comment by subhangiP** [comment]
Hello @QB-nikolay-zolotarov,

I have created Apple push Notifications service SSL (Sandbox & Production). Is it APNS universal certificate?
Is it enough for both **audio calling** and c**hat functionality**.

**Comment by ghost** [comment]
@subhangiP It should be enough
