### ISSUE TITLE
The very first time I got a call, I got a prompt for Camera. This prompt needs to be disabled.

### ISSUE THREAD

**Issue by subhangiP** [QuickBlox/quickblox-flutter-samples#14]
<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: 600;">Environment details</strong></p>

Info | Value
-- | --
iOS Version | 15.0.2
Quickblox iOS SDK version | 2.17.10'
QuickbloxWebRTC SDK version | 2.7.6'
Xcode Version | e.g. Xcode 13.0

**Project descriptions **

This is our flutter app which has audio call and chat functionality using quickblox-flutter as well as quickblox-iOS SDK that is
working fine.
For chat, we are using [quickblox flutter SDK](https://github.com/QuickBlox/quickblox-flutter-samples) - working fine
For audio calls, we are using [quickblox iOS SDK](https://github.com/QuickBlox/quickblox-ios-sdk) using the method channel
in native iOS - working fine
Our app does require camera access to update the profile pic and that permission we are asking to user while adding the profile pic.
The issue is if user didn’t add profile pic and receives a call the very first time time, there will be prompt for camera permission.
Why there is camera permission prompt in audio call is recieve. we have follow same iOS sample project to implement audio call functionality? Is it becoz [quickblox flutter SDK](https://github.com/QuickBlox/quickblox-flutter-samples) because it requires all Camera, Microphone, Storage permissions to enable
Expected behavior
This prompt needs to be disabled.

Actual behavior
The camera permission prompt is displaying first time when call notifications is receive.

PFA SS for the same issue.
![camera_popup](https://user-images.githubusercontent.com/40853201/171826118-3939d42d-9be5-44ae-be7b-c7d65febc02c.PNG)

**Comment by ghost** [comment]
Hello Subhangi, this is Nikolay from QuickBlox support.
Please clarify if you are using the QuickBlox Flutter SDK for audio calls as well and if the issue is reproduced on the QuickBlox Flutter SDK.

**Comment by subhangiP** [comment]
@QB-nikolay-zolotarov, I am using quickblox flutter SDK only for chat and For audio calls, we are using [quickblox iOS SDK](https://github.com/QuickBlox/quickblox-ios-sdk) using the method channel in our flutter project.

**Comment by ghost** [comment]
@subhangiP We don't have experience in using both SDKs at the same time. At this point, I can suggest using our samples where this functionality works as expected:
https://docs.quickblox.com/docs/code-samples#video-calling-samples
