### ISSUE TITLE
Hanging up the first call when another call comes in during a call

### ISSUE THREAD

**Issue by furkanerkl** [QuickBlox/quickblox-flutter-samples#19]
I plan to get the ids of the active calls and close the first call with the hangup function, but I can't figure out how to get the id of the first call. Do you have any suggestions on this?

**Comment by kirillTolmachev** [comment]
Hello @furkanerkl 
The **id** of call it's **sessionId**
You can get **sessionId** from received CALL event. 

```
await QB.webrtc.subscribeRTCEvent(QBRTCEventTypes.CALL, (data) {
        Map<dynamic, dynamic> payloadMap = Map<dynamic, dynamic>.from(data["payload"]);
        Map<dynamic, dynamic> sessionMap = Map<dynamic, dynamic>.from(payloadMap["session"]);

        String sessionId = sessionMap["id"];
 }
```

Link to github [code](https://github.com/QuickBlox/quickblox-flutter-samples/blob/550c79df5aef68ffc96f36b8a35cb132d4f63c69/simple_sample/lib/screens/webrtc_screen.dart#L396)

**Comment by kirillTolmachev** [comment]
@furkanerkl 
Closed due to no feedback
