### ISSUE TITLE
Not able to install quickblox_sdk: ^0.6.0-beta in app.

### ISSUE THREAD

**Issue by KushalxPathak** [QuickBlox/quickblox-flutter-samples#6]
When I import example from https://github.com/QuickBlox/quickblox-flutter-samples it works fine and runs in iOS simulator.

But when I tried installing it in one of the app I am working on it shows error only for this package quickblox_sdk as soon as I comment and run the project it works like a charm.

Works fine on android physical device.Only issue in iOS simulator.

My fluter version : Channel stable, 2.5.1
Dart SDK version: 2.14.2
iOS simulator: 12 pro mx (iOS version 14.5)

Logs I am getting while running the app for simulator

Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running Xcode build...
Xcode build done.                                            9.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    ld: warning: ignoring file /Users/admin/Desktop/Projects/fit_now/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/Quickblox/Quickblox.framework/Quickblox, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
    ld: warning: ignoring file /Users/admin/Desktop/Projects/fit_now/build/ios/Debug-iphonesimulator/XCFrameworkIntermediates/QuickbloxWebRTC/QuickbloxWebRTC.framework/QuickbloxWebRTC, building for iOS Simulator-arm64 but attempting to link with file built for iOS Simulator-x86_64
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_QBRTCClient", referenced from:
          objc-class-ref in QBWebRTCModule.o
          objc-class-ref in QBWebRTCSessionController.o
      "_OBJC_CLASS_$_QBUpdateUserParameters", referenced from:
          objc-class-ref in QBUsersModule.o
      "_QuickbloxFrameworkVersion", referenced from:
          -[QBSettingsModule get:rejecter:] in QBSettingsModule.o
      "_OBJC_CLASS_$_QBRTCSession", referenced from:
          __OBJC_$_CATEGORY_QBRTCSession_$_QBSerializer in QBRTCSession+QBSerializer.o
      "_OBJC_METACLASS_$_QBRTCRemoteVideoView", referenced from:
          _OBJC_METACLASS_$_QBWebRTCVideoView in QBWebRTCVideoView.o
      "_OBJC_CLASS_$_QBRTCConferenceSession", referenced from:
          __OBJC_$_CATEGORY_QBRTCConferenceSession_$_QBSerializer in QBRTCConferenceSession+QBSerializer.o
      "_OBJC_CLASS_$_QBRTCConfig", referenced from:
          objc-class-ref in QBConferenceModule.o
          objc-class-ref in QBRTCConfigModule.o
         (maybe you meant: _OBJC_CLASS_$_QBRTCConfigModule)
      "_OBJC_CLASS_$_QBResponse", referenced from:
          __OBJC_$_CATEGORY_QBResponse_$_Helper in QBResponse+Helper.o
      "_OBJC_CLASS_$_QBRTCAudioSession", referenced from:
          objc-class-ref in QBConferenceModule.o
          objc-class-ref in QBWebRTCModule.o
      "_OBJC_CLASS_$_QBRTCConferenceClient", referenced from:
          objc-class-ref in QBConferenceModule.o
      "_OBJC_CLASS_$_QBSettings", referenced from:
          objc-class-ref in QBSettingsModule.o
         (maybe you meant: _OBJC_CLASS_$_QBSettingsModule, _OBJC_CLASS_$_QBSettingsConstants )
      "_OBJC_CLASS_$_QBRTCCameraCapture", referenced from:
          objc-class-ref in QBConferenceWrapper.o
          objc-class-ref in QBWebRTCSessionController.o
      "_OBJC_CLASS_$_QBCOCustomObject", referenced from:
          __OBJC_$_CATEGORY_QBCOCustomObject_$_QBSerializer in QBCOCustomObject+QBSerializer.o
          objc-class-ref in QBCustomObjectsModule.o
      "_OBJC_CLASS_$_QBCOPermissions", referenced from:
          objc-class-ref in QBCOCustomObject+QBSerializer.o
      "_OBJC_CLASS_$_QBUUser", referenced from:
          objc-class-ref in QBUsersModule.o
          __OBJC_$_CATEGORY_QBUUser_$_QBSerializer in QBUUser+QBSerializer.o
      "_OBJC_CLASS_$_QBResponsePage", referenced from:
          objc-class-ref in QBChatModule.o
          objc-class-ref in QBChatModule+Dialogs.o
          objc-class-ref in QBChatModule+Messages.o
          __OBJC_$_CATEGORY_QBResponsePage_$_QBSerializer in QBResponsePage+QBSerializer.o
      "_OBJC_CLASS_$_QBChat", referenced from:
          objc-class-ref in QBChatModule.o
          objc-class-ref in QBChatModule+Connection.o
          objc-class-ref in QBChatModule+Messages.o
          objc-class-ref in QBChatModule+Ping.o
          objc-class-ref in QBWebRTCModule.o
         (maybe you meant: _OBJC_CLASS_$_QBChatConstants, _OBJC_CLASS_$_QBChatModule )
      "_OBJC_CLASS_$_QBRTCVideoFormat", referenced from:
          objc-class-ref in QBConferenceWrapper.o
          objc-class-ref in QBWebRTCSessionController.o
      "_OBJC_CLASS_$_QBGeneralResponsePage", referenced from:
          __OBJC_$_CATEGORY_QBGeneralResponsePage_$_QBSerializer in QBGeneralResponsePage+QBSerializer.o
          objc-class-ref in QBNotificationEventsModule.o
          objc-class-ref in QBUsersModule.o
      "_OBJC_CLASS_$_QBChatMessage", referenced from:
          __OBJC_$_CATEGORY_QBChatMessage_$_QBSerializer in QBChatMessage+QBSerializer.o
          objc-class-ref in QBChatModule+Messages.o
      "_OBJC_CLASS_$_QBRTCAudioSessionConfiguration", referenced from:
          objc-class-ref in QBConferenceModule.o
          objc-class-ref in QBWebRTCModule.o
      "_OBJC_CLASS_$_QBChatDialog", referenced from:
          __OBJC_$_CATEGORY_QBChatDialog_$_QBSerializer in QBChatDialog+QBSerializer.o
          objc-class-ref in QBChatModule.o
          objc-class-ref in QBChatModule+Dialogs.o
      "_OBJC_CLASS_$_QBSession", referenced from:
          objc-class-ref in QBAuthModule.o
          objc-class-ref in QBChatModule.o
          __OBJC_$_CATEGORY_QBSession_$_QBSerializer in QBSession+QBSerializer.o
      "_OBJC_CLASS_$_QBRequest", referenced from:
          objc-class-ref in QBAuthModule.o
          objc-class-ref in QBChatModule.o
          objc-class-ref in QBChatModule+Dialogs.o
          objc-class-ref in QBChatModule+Messages.o
          objc-class-ref in QBCustomObjectsModule.o
          objc-class-ref in QBFileModule.o
          objc-class-ref in QBNotificationEventsModule.o
          ...
      "_OBJC_CLASS_$_QBChatAttachment", referenced from:
          objc-class-ref in QBChatAttachment+QBSerializer.o
          __OBJC_$_CATEGORY_QBChatAttachment_$_QBSerializer in QBChatAttachment+QBSerializer.o
          objc-class-ref in QBChatModule+Messages.o
      "_OBJC_CLASS_$_QBRTCRemoteVideoView", referenced from:
          _OBJC_CLASS_$_QBWebRTCVideoView in QBWebRTCVideoView.o
      "_OBJC_CLASS_$_QBCBlob", referenced from:
          __OBJC_$_CATEGORY_QBCBlob_$_QBSerializer in QBCBlob+QBSerializer.o
          objc-class-ref in QBFileModule.o
      "_OBJC_CLASS_$_QBMSubscription", referenced from:
          objc-class-ref in QBMSubscription+QBSerializer.o
          __OBJC_$_CATEGORY_QBMSubscription_$_QBSerializer in QBMSubscription+QBSerializer.o
          objc-class-ref in QBPushSubscriptionsModule.o
      "_OBJC_CLASS_$_QBASession", referenced from:
          objc-class-ref in QBAuthModule.o
      "_OBJC_CLASS_$_QBMEvent", referenced from:
          objc-class-ref in QBMEvent+QBSerializer.o
          __OBJC_$_CATEGORY_QBMEvent_$_QBSerializer in QBMEvent+QBSerializer.o
          objc-class-ref in QBNotificationEventsModule.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete

Could not build the application for the simulator.
Error launching application on iPhone 12 Pro Max.

**Comment by ghost** [comment]
@KushalxPathak Hello,

This is Nikolay from QuickBlox support.

Please make sure that you followed our documentation:
[https://docs.quickblox.com/docs/flutter-quick-start](https://docs.quickblox.com/docs/flutter-quick-start)
[https://docs.quickblox.com/docs/flutter-setup](https://docs.quickblox.com/docs/flutter-setup)

Also, please specify the version of the QuickBlox Flutter SDK. Please make sure that you use the latest version:
[https://pub.dev/packages/quickblox_sdk/versions/0.6.3-beta](https://pub.dev/packages/quickblox_sdk/versions/0.6.3-beta)

**Comment by ghost** [comment]
@KushalxPathak Please let me know if you fixed the issue and provide me with more information

**Comment by santiagomartinp** [comment]
I have very similar issue, @KushalxPathak how did you solve it? thanks!
