### ISSUE TITLE
Crash app after init method of quickblox in flutter 

### ISSUE THREAD

**Issue by geetakher** [QuickBlox/quickblox-flutter-samples#9]
**Please find below logs for the crash issue**

(13156): initClass exception com.quickblox.messages.QBPushNotifications
D/QBASDK  (13156): Restored custom endpoints. ApiEndpoint: , ChatEndpoint: . lastUpdateTime: Thu Jan 01 05:30:00 GMT+05:30 1970
D/QBASDK  (13156): DEVICE_ID = 00000000-5bf4-51e3-ffff-fffff3653a67
D/QBASDK  (13156): creating app secured preferences
D/QBASDK  (13156): There is no information about chat server endpoint, use the default one.
D/QBASDK  (13156): There is no information about chat server endpoint, use the default one.
W/j.b.a.o (13156): A startup class 'org.jivesoftware.smack.initializer.VmArgInitializer' could not be loaded.
D/TransportRuntime.SQLiteEventStore(13156): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler(13156): Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=-2043857720 in 1000ms(Backend next call timestamp 0). Attempt 1
E/AndroidRuntime(13156): FATAL EXCEPTION: main
E/AndroidRuntime(13156): Process: com.human.quest.human_quest, PID: 13156
E/AndroidRuntime(13156): java.lang.ExceptionInInitializerError
E/AndroidRuntime(13156): 	at j.b.a.m.h(Unknown Source:0)
E/AndroidRuntime(13156): 	at j.b.a.d.<clinit>(Unknown Source:0)
E/AndroidRuntime(13156): 	at c.i.b.g.<clinit>(Unknown Source:0)
E/AndroidRuntime(13156): 	at c.i.b.g.c0(Unknown Source:0)
E/AndroidRuntime(13156): 	at c.i.h.n.b.h(:117)
E/AndroidRuntime(13156): 	at c.i.h.n.b.g(:64)
E/AndroidRuntime(13156): 	at c.i.h.n.a.onMethodCall(Unknown Source:2)
E/AndroidRuntime(13156): 	at e.a.c.a.j$a.a(:233)
E/AndroidRuntime(13156): 	at io.flutter.embedding.engine.f.b.e(:84)
E/AndroidRuntime(13156): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:865)
E/AndroidRuntime(13156): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(13156): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(13156): 	at android.os.Looper.loop(Looper.java:206)
E/AndroidRuntime(13156): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
E/AndroidRuntime(13156): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13156): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(13156): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/AndroidRuntime(13156): Caused by: java.lang.IllegalStateException: java.lang.ClassNotFoundException: org.jivesoftware.smack.initializer.VmArgInitializer
E/AndroidRuntime(13156): 	at j.b.a.o.<clinit>(Unknown Source:213)
E/AndroidRuntime(13156): 	... 17 more
E/AndroidRuntime(13156): Caused by: java.lang.ClassNotFoundException: org.jivesoftware.smack.initializer.VmArgInitializer
E/AndroidRuntime(13156): 	at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(13156): 	at java.lang.Class.forName(Class.java:454)
E/AndroidRuntime(13156): 	at j.b.a.o.a(Unknown Source:1)
E/AndroidRuntime(13156): 	at j.b.a.o.b(Unknown Source:34)
E/AndroidRuntime(13156): 	at j.b.a.o.d(Unknown Source:39)
E/AndroidRuntime(13156): 	at j.b.a.o.c(Unknown Source:6)
E/AndroidRuntime(13156): 	at j.b.a.o.<clinit>(Unknown Source:153)
E/AndroidRuntime(13156): 	... 17 more
E/AndroidRuntime(13156): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jivesoftware.smack.initializer.VmArgInitializer" on path: DexPathList[[zip file "/data/app/~~QMQRnqRRIcbpT5tHLsQNLQ==/com.human.quest.human_quest-78PUv4yG5uDFN7m1wZA7Iw==/base.apk"],nativeLibraryDirectories=[/data/app/~~QMQRnqRRIcbpT5tHLsQNLQ==/com.human.quest.human_quest-78PUv4yG5uDFN7m1wZA7Iw==/lib/arm64, /data/app/~~QMQRnqRRIcbpT5tHLsQNLQ==/com.human.quest.human_quest-78PUv4yG5uDFN7m1wZA7Iw==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/AndroidRuntime(13156): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
E/AndroidRuntime(13156): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(13156): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(13156): 	... 24 more
I/Process (13156): Sending signal. PID: 13156 SIG: 9
Lost connection to device.

**flutter SDK verison :- 2.5.2
 quickblox_sdk: ^0.6.5-beta**
 
 
 **Below code for init quickbox** 
 Future<void> init_quick_cred() async {
    try {
      await QB.settings.init(Q_APP_ID, Q_AUTH_KEY, Q_AUTH_SECRET, Q_ACCOUNT_KEY);
     // login_quick();
    } on PlatformException catch (e) {
      showToastBottom(e.message!);

    }
  }

**Comment by ghost** [comment]
@geetakher Hello,

This is Nikolay from QuickBlox support.

According to the provided log, the issue may be caused by Proguard.

Please try disabling Proguard and releasing the app.

You may try adding this flag: --no-shrink

**Comment by geetakher** [comment]
ok done

**Comment by UnderKoen** [comment]
For anybody else facing this problem and the `--no-shrink` flag not fixing the issue. I fixed this by creating `proguard-rules.pro` in `android/app`

`android/app/proguard-rules.pro`
```
#QuickBlox
-keep class org.jivesoftware.smack.initializer.VmArgInitializer { public *; }

##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-keep class sun.misc.Unsafe { *; }
#-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class com.quickblox.core.account.model.** { *; }

#quickblox sample chat
-keep class com.quickblox.auth.parsers.** { *; }
-keep class com.quickblox.auth.model.** { *; }
-keep class com.quickblox.core.parser.** { *; }
-keep class com.quickblox.core.model.** { *; }
-keep class com.quickblox.core.server.** { *; }
-keep class com.quickblox.core.rest.** { *; }
-keep class com.quickblox.core.error.** { *; }
-keep class com.quickblox.core.Query { *; }

-keep class com.quickblox.users.parsers.** { *; }
-keep class com.quickblox.users.model.** { *; }

-keep class com.quickblox.chat.parser.** { *; }
-keep class com.quickblox.chat.model.** { *; }

-keep class com.quickblox.messages.parsers.** { *; }
-keep class com.quickblox.messages.model.** { *; }

-keep class com.quickblox.content.parsers.** { *; }
-keep class com.quickblox.content.model.** { *; }

-keep class org.jivesoftware.** { *; }

 #sample chat
-keep class android.support.v7.** { *; }
-keep class com.bumptech.** { *; }

-dontwarn org.jivesoftware.smackx.**
-dontwarn android.support.v4.app.**
```
[original non flutter](https://stackoverflow.com/questions/32594915/quickblox-and-pro-guard-error)
